name: Keep Server Alive

on:
  schedule:
    # Run every 1 minute
    - cron: '*/1 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping-server:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping TuneDrop Backend
      run: |
        curl -X GET https://tunedrop.onrender.com/api/health \
          -H "User-Agent: GitHub-Actions-KeepAlive/1.0" \
          --max-time 30 \
          --retry 3 \
          --retry-delay 5
      
    - name: Log Status
      run: |
        echo "✅ Server pinged at $(date)"
        echo "🎯 URL: https://tunedrop.onrender.com/api/health"
        echo "⏰ Next ping in 1 minute"
